### ISSUE TITLE
Musl builds fail

### ISSUE THREAD

**Issue by tibequadorian** [BuddiesOfBudgie/budgie-screensaver#14]
Noticed while updating for Void Linux, musl builds are failing again:
https://github.com/void-linux/void-packages/actions/runs/3553122553/jobs/5968457967

This is because my change in https://github.com/BuddiesOfBudgie/budgie-screensaver/pull/4 got reverted in https://github.com/BuddiesOfBudgie/budgie-screensaver/commit/78799a0c4861d8e5577b80952c7407bd002f7f9a.

**Comment by serebit** [comment]
Oh, yep, my bad. Sorry about that.

**Comment by serebit** [comment]
I've added a GitHub Actions job that builds on Alpine Linux in 4894e97 to ensure that we know if we break musl builds again.
