### ISSUE TITLE
[Transifex] Portuguese language

### ISSUE THREAD

**Issue by hugok79** [BuddiesOfBudgie/budgie-screensaver#17]
@serebit @JoshStrobl
The **Portuguese** language and the **Portuguese (Portugal**) are the same, so there is no need to have the **Portuguese** `pt` translation file in https://www.transifex.com/buddiesofbudgie/dashboard/all_projects/pt/ because the **Portuguese (Portugal)** `pt_PT` file already exists.

Also because in Transifex https://www.transifex.com/buddiesofbudgie/ the **Portuguese** `pt` language only contains the `budgie-screensaver` translation.

Leave only the Portuguese (Portugal) `pt_PT` language https://www.transifex.com/buddiesofbudgie/dashboard/all_projects/pt_PT/

Thanks in advance!

**Comment by serebit** [comment]
Took your word for it and removed `pt`. `pt_BR` and `pt_PT` are still present. Thanks for the heads up!
