### ISSUE TITLE
Changing language on lock screen not possible

### ISSUE THREAD

**Issue by mike-ua** [BuddiesOfBudgie/budgie-screensaver#6]
My comment added to the Solus forums, but user 'Nolan' says it's a Budgie issue, not Solus.

Hi,
I have the same issue (Solus/Budgie) - when coming back from 'Suspend', and the language was left in another that was not English (my 'unlock' password' is in English) there is no longer the option to switch languages. It was there before, used it many times.

The only way to resolve the issue is to hold the power button down and kill the computer, a fairly substantial regression that significantly affects usability.

Here is the link to the issue reported in the Solus forums - https://discuss.getsol.us/d/8187-changing-language-on-lock-screen

Thanks
Mike

**Comment by mike-ua** [comment]
gsettings get org.gnome.desktop.input-sources sources
returns:
[('xkb', 'us'), ('xkb', 'ua')]

gsettings get org.gnome.desktop.input-sources current
returns:
uint32 0

**Comment by fossfreedom** [comment]
Thx. So the inputs look OK.

To resolve this will need a series of debug statements in the area of the  code i pointed to to find out what is going on. This will need to be done on Solus ... I can't do this since debian and budgie doesn't use budgie-screensaver.

**Comment by mike-ua** [comment]
unfortunately, I do not know how to do this, is it difficult to produce a 'debug statement'?  Maybe you can give me some instructions and I can try.

**Comment by EbonJaeger** [comment]
If @fossfreedom can tell me where the prints need to be, I can make a quick testing package for you to try.

**Comment by Solarunit** [comment]
>The only way to resolve the issue is to hold the power button down and kill the computer,

There is another "workaround". 
Left button (Switch user iirc) will take you to the Login screen where you can reboot system.
(You can bypass the Login screen but would stuck at locks-screen again, so reboot is only option)

**Comment by mike-ua** [comment]
> > The only way to resolve the issue is to hold the power button down and kill the computer,
> 
> There is another "workaround". Left button (Switch user iirc) will take you to the Login screen where you can reboot system. (You can bypass the Login screen but will stuck at lock-screen again, so reboot is only option)

That's basically the same as holding the power button down, less abrupt, but still a disruption to work flow.  Strange part is that I know the option to switch languages was there before, so at some point this (necessary) feature was eliminated for whatever reasons.
