### ISSUE TITLE
Audit build options from the pre-meson configure.ac

### ISSUE THREAD

**Issue by EbonJaeger** [BuddiesOfBudgie/budgie-screensaver#7]
In the process of fixing #6, I noticed there were other options that the old configure.ac file had that we don't have now. The old file can be viewed [here](https://github.com/BuddiesOfBudgie/budgie-screensaver/blob/19b0852297f3b8a45e1e6773212adb1de0dd3216/configure.ac).

Options:
- [ ] `mit-ext`: Include support for the MIT-SCREEN-SAVER extension
- [ ] `xf86gamma-ext`: Include support for XFree86 gamma fading
- [ ] `no-locking`
  - `--enable-locking`: Compile in support for locking the display
  - `--disable-locking`: Do not allow locking at all
- [ ] `console-kit`: Add ConsoleKit support

Some of these may not be wanted or necessary based on our targets/use cases.

**Comment by serebit** [comment]
Addressed with a550495.
