### ISSUE TITLE
Unable to change keyboard layout

### ISSUE THREAD

**Issue by XInvisib1eX** [BuddiesOfBudgie/budgie-screensaver#8]
Solus 4.3
GNOME 42.0

You're not able to change language in lock screen, so you're in trouble to unlock in situation when you forgot to change language back to English. (Instead of changing the language `Super + Space` provided space character, `Alt + Shift` doesn't work in screensaver as well)

Steps to reproduce the issue

1. Add Russian language in Settings-Region&Language-InputSources.
2. `Super + Space` to change language to Russian.
3. `Super + L` to lock the screen.
4. You're in trouble to unlock, because you are not able to change language.

There was special button to the right of password input that allows to change language before, but it vanished after some update. Now I have to login to console and change keyboard layout via `gsettings set org.gnome.desktop.input-sources current 0`.

Also I tried to make custom shortcut for this command, but screensaver prevents you from using shortcuts.

**Comment by EbonJaeger** [comment]
This should have been fixed on Solus as of the last sync. Could you please make sure that your system is fully up-to-date? Also, you say GNOME 42... I'm assuming you mean Budgie 10.6.1?

**Comment by EbonJaeger** [comment]
Correction: The control is there, but the given shortcut indeed doesn't appear to be working...

**Comment by XInvisib1eX** [comment]
Well, I don't remember when this functionality disappeared (but it had been absent for a long time) , but after last update it returned back, thanks!
